# language
lang: "ita"

# bluetooth device name (can also be a part of the actual name, e.g. "Pixel" also works for "Pixel Buds", "Pixel Buds A series", "Pixel phone" and so on)
device_name: "NS7"

# player settings
start_track: 3
volume_steps: 5
bt_volume: 50

# distance sensor
distance_sensor_enabled: False
threshold: 250
echo_pin: 24
trig_pin: 23

# pause button
button_pin: 27

# bluetooth volume rotary encoder
dt_pin: 17
clk_pin: 18
