# language
lang: "ita"

# bluetooth device name (can also be a part of the actual name, e.g. "Pixel" also works for "Pixel Buds", "Pixel Buds A series", "Pixel phone" and so on)
device_name: "NS7"

# player settings
start_track: 1
volume_steps_um: "perc" # unit of measure of volume steps: perc|db
volume_steps: 2
bt_volume: 20
fr_volume: 50

# Buttons
# Front track
fr_tr_button: 19
# bluetooth track
bg_tr_button: 5
# Front volume up
fr_vol_up_button: 23
# Front volume down
fr_vol_down_button: 4

